sudo: required

services:
  - docker

language: generic

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

before_script:
  - docker --version
  - aws --version

script:
  ./Scripts/Publish.sh
