DROP DATABASE IF EXISTS $DB WITH (FORCE);
DROP ROLE IF EXISTS $USERNAME;

CREATE DATABASE $DB
WITH OWNER adminuser;

REVOKE connect ON DATABASE $DB FROM PUBLIC;

 \connect $DB;

CREATE ROLE $USERNAME
LOGIN
PASSWORD '$PASSWORD';
