\connect $DB;

GRANT connect ON DATABASE $DB TO $USERNAME;
ALTER SCHEMA public RENAME TO $SCHEMA_NAME;
ALTER SCHEMA $SCHEMA_NAME OWNER TO $USERNAME;
GRANT ALL PRIVILEGES ON SCHEMA $SCHEMA_NAME TO $USERNAME;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $SCHEMA_NAME TO $USERNAME;
ALTER USER $USERNAME SET search_path = $SCHEMA_NAME;
